# Generated by Django 4.1.1 on 2022-10-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_delete_userinf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BooksInf',
        ),
    ]
