# Generated by Django 4.1.1 on 2022-10-01 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BooksInf',
        ),
    ]
