# Generated by Django 4.1.1 on 2022-10-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_delete_booksinf'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksInf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=64)),
                ('bauthor', models.CharField(max_length=32)),
                ('bimg', models.CharField(max_length=1024)),
                ('bstate', models.CharField(max_length=32)),
            ],
        ),
    ]
