# Generated by Django 4.1.1 on 2022-10-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_booksinf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInf',
        ),
    ]
